---
- name: add splunk group
  group:
    name: "{{ splunk.group }}"
    state: present

- name: add splunk user
  user:
    name: "{{ splunk.user }}"
    comment: "Splunk service user"
    shell: "/usr/sbin/nologin"
    groups: "{{ splunk.group }}"
    createhome: true

- name: make /opt writetable by splunk
  file:
    path: "/opt"
    mode: 0777

- name: Gather package facts
  package_facts:
    manager: auto

- name: splunk upgrade tasks
  include_tasks: splunk-upgrade.yml
  when:
    ('splunk' in ansible_facts.packages)

- name: Install splunk package
  dnf:
    name: "{{ splunk_rpm_url }}"
    state: present
  register: splunk_rpm_installed

- name: set splunk.secret file
  template:
    src: splunk.secret.j2
    dest: /opt/splunk/etc/auth/splunk.secret
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0400
  notify: restart splunk

- name: systemd setup
  include_tasks: systemd.yml
  when:
    - ansible_service_mgr == "systemd"

- name: touch ui so it does not ask for the password to be changed
  file:
    path: /opt/splunk/etc/.ui_login
    state: touch
  become: true
  become_user: "{{ splunk.user }}"
  when: splunk_rpm_installed.changed
